### ISSUE TITLE
Java File Seperator

### ISSUE THREAD

**Issue by rmattler** [raghavendar-ts/ElasticTab-Elasticsearch-to-Excel-Report#1]
In your App and LoadConfigurationListener classes you are using the windows file separator.  Please modify your code to use the platform dependent separator.  I.E.  "/" for linux and "\" for windows.  By changing these 2 classes I was able to install ElasticTab on linux!

public class App {
    public static void main(String[] args) {
        String jarPath = System.getProperties().getProperty("user.dir");
        System.out.println("Property files loaded from the path " + jarPath);

```
    JettyServerEmbedded jettyServerEmbedded = new JettyServerEmbedded(jarPath + File.separatorChar  +  "properties" + File.separatorChar + "jetty.properties");
    jettyServerEmbedded.start();

    H2DatabaseEmbedded h2DatabaseEmbedded = new H2DatabaseEmbedded(jarPath + File.separatorChar  + "properties" + File.separatorChar  + "h2.properties");

    QuartzServerEmbedded quartzServerEmbedded = new QuartzServerEmbedded(jarPath +  File.separatorChar  + "properties" + File.separatorChar  + "quartzServer.properties");
    quartzServerEmbedded.start();
}
```

}

public class LoadConfigurationListener implements ServletContextListener {
    Properties properties = new Properties();

```
public void contextInitialized(ServletContextEvent sce) {
    ServletContext context = sce.getServletContext();
    String hostname = "localhost";
    String jarPath = System.getProperties().getProperty("user.dir");

    try {
        InputStream input = new FileInputStream(jarPath + File.separatorChar  + "properties" + File.separatorChar  + "elasticsearch.properties");
```

**Comment by raghavendar-ts** [comment]
The issue is fixed
