### ISSUE TITLE
File separator in LoadConfigurationListener also needs to be fixed

### ISSUE THREAD

**Issue by rmattler** [raghavendar-ts/ElasticTab-Elasticsearch-to-Excel-Report#2]
public class LoadConfigurationListener implements ServletContextListener {
Properties properties = new Properties();

public void contextInitialized(ServletContextEvent sce) {
    ServletContext context = sce.getServletContext();
    String hostname = "localhost";
    String jarPath = System.getProperties().getProperty("user.dir");

```
try {
    InputStream input = new FileInputStream(jarPath + File.separatorChar  + "properties" + File.separatorChar  + "elasticsearch.properties");
```

**Comment by raghavendar-ts** [comment]
The class LoadConfigurationListener was used to load Elasticsearch connection. Now loading the connection is moved to the class ESReport
