### ISSUE TITLE
buttons is greyed out.

### ISSUE THREAD

**Issue by ajrpayne** [raghavendar-ts/ElasticTab-Elasticsearch-to-Excel-Report#3]
I have elastictab running. However, all buttons but download report are greyed out. Is there something I am missing?

**Comment by raghavendar-ts** [comment]
You must fill in report name, file name, select index and type. This should enable the download button

**Comment by ajrpayne** [comment]
Sorry, let me clarify. I mean all other buttons are greyed out. I can download the report just fine. But I can't schedule a job or update a job.

**Comment by raghavendar-ts** [comment]
Perform these operations
1. Enable E-Mail option
2. Schedule option
3. Enter email subject
4. Enter atleast one valid email
5. Enter atleast one CRON schedule.

you will now have E-Mail and Schedule button enabled.

On Tue, Feb 2, 2016 at 11:31 AM, ajrpayne notifications@github.com wrote:

> Sorry, let me clarify. I mean all other buttons are greyed out. I can
> download the report just fine. But I can't schedule a job or update a job.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/raghavendar-ts/ElasticTab-Elasticsearch-to-Excel-Report/issues/3#issuecomment-178390735
> .

## 

Raghavendar T S
www.teknosrc.com

**Comment by raghavendar-ts** [comment]
Can I close the ticket?

**Comment by ajrpayne** [comment]
Yes, you can close this ticket. 
Thank you for the help.
